# Generated by Django 4.0.6 on 2022-07-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_news'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
