# Generated by Django 4.0.6 on 2022-07-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name_plural': 'Setting'},
        ),
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
    ]
