# Generated by Django 4.0.6 on 2022-07-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
