# Generated by Django 4.0.6 on 2022-07-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
    ]
